[pytest]
markers =
    smoke: Дымовые тесты для критического функционала
    regression: Полный набор регрессионных тестов
    slow: Медленные тесты (например, с доступом к сети или к база данных)
    temp: Временные тесты, которые могут быть удалены в будущем
    db_connect: Тесты, которые требуют подключения к базе данных
